#!/usr/bin/env bash
# PYTHON_ARGCOMPLETE_OK
# ^ is about auto-completion, see https://argcomplete.readthedocs.io/en/latest/#global-completion

# Forward all to Python Command Line Interface
# e.g.
#
# * help output:
# ./erika_sh -h
# ./erika_sh render_ascii_art -h
#
# * demo output
# ./erika_sh demo -p "COM3"
# ./erika_sh demo -p "/dev/ttyACM0"
#
# * simulation + "on-screen cinematics"
# ./erika_sh render_ascii_art -d -f ./tests/test_resources/test_ascii_art.txt -s PerpendicularSpiralInward -p 'fake_port'
# ./erika_sh render_ascii_art -d -f ./tests/test_resources/test_ascii_art.txt -s ArchimedeanSpiralOutward  -p 'fake_port'
# ./erika_sh render_ascii_art -d -f ./tests/test_resources/test_ascii_art.txt -s RandomDotFill  -p 'fake_port'
#
# * real output
# ./erika_sh render_ascii_art -p "COM3" -f ./tests/test_resources/test_ascii_art_small.txt
# ./erika_sh render_ascii_art -p "/dev/ttyACM0" -f ./tests/test_resources/test_ascii_art_small.txt -s PerpendicularSpiralInward
python3 -m erika.cli $@